print("일반 계산기 프로그램입니다.")
first = float(input("계산할 첫번째 값을 입력해주세요: "))
second = float(input("계산할 두번째 값을 입력해주세요: "))

print("두개의 값: ", first, "와", second)
print(" ")
print("더하기 값(a+b): ", first+second )
print("빼기 값(a-b): ", first-second)
print("곱하기 값(a*b): ", first*second)
print("나누기 값(a//b): ", first//second) 
print("실수 나누기 값(a/b): ", first/second)
print("나머지 값:(a%b): ", first%second)